version: '3.8'

services:
  postgres_test_db:
    image: postgres:14.2-alpine
    container_name: postgres_test_db
    ports:
      - ${POSTGRES_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
