version: '3.8'

services:
  app:
    build:
      target: stage
    volumes:
      - /app/node_modules
      - /app/build

    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4g
  postgres:
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4g
