version: '3.8'

services:
  app:
    build:
      context: .
      target: prod
    ports:
      - ${PORT}:${PORT}
    volumes:
      - /app/node_modules
      - /app/build
    network_mode: 'host'
    restart: always
