export default {
  userAlreadyExists: 'User already exists',
  idRequired: 'Id is required',
  userNotFound: 'User not found',
  emailRequired: 'Email required',
  passwordRequired: 'Password required',
  firstNameRequired: 'Firstname required',
  lastNameRequired: 'Lastname required',
  emailNotValid: 'Email not valid',
  phoneRequired: 'Phone required',
  resourceNotFound: 'Resource not found',
  rolesRequired: 'Roles required',
  userCreateRoleNotFound: 'One of the roles is not a valid role',
  tokenRequired: 'Token required',
  userNotAuthenticated: 'User not authenticated',
  emailPasswordNotCorrect: 'Email or password is not correct',
  notAllowedToCreateAdmin: 'User is not allowed to create admin',
  tokenTypeRequired: 'Token type required',
  expiresInNotValid: 'Argument expiresIn is not valid',
  userIdRequired: 'User id is required',
  tokenInvalid: 'Token is invalid',
  startDateRequired: 'Start Date required',
  endDateRequired: 'End Date required',
  payRateRequired: 'PayRate required',
  companyNotFound: 'Company not found',
  companyCodeExists: 'Company code already exists',
  pleaseLoginWithCompany: 'Please login with your respective company',
  invitationAlreadyExists: 'Invitation already exists',
  inviterRequired: 'Inviter required',
  companyRequired: 'Company required',
  userAlreadyExistsInCompany: 'User already exists',
  notAllowedToPerformAction: 'User is not allowed to perform the action',
  canOnlyInviteToOwnCompany: 'User can only invite to its own workspace',
  canOnlyViewOwnCompany: 'User can only view its own company invitations',
  canOnlyCreateOnOwnCompany: 'User can only create on its own workspace',
  recordRequired: 'Record is required',
  nameRequired: 'Name required',
  managerIdRequired: 'Manager Id required',
  companyIdRequired: 'Company Id required',
  statusRequired: 'Status Required',
  taskIdRequired: 'Task Id required',
  EmployeeIdRequired: 'Employee Id required',
  taskNotFound: 'Task not found',
  invitationNotFound: 'Invitation not found',
  roleRequired: 'Role required',
  invitationExpired: 'Invitation expired',
  alreadyAssigned: 'Assigned task couldn`t change status',
  companyArchived: 'Company is archived',
};
