export default {
  userAlreadyExists: 'User already exists',
  idRequired: 'Id is required',
  userNotFound: 'User not found',
  emailRequired: 'Email required',
  passwordRequired: 'Password required',
  firstNameRequired: 'Firstname required',
  lastNameRequired: 'Lastname required',
  emailNotValid: 'Email not valid',
  phoneRequired: 'Phone required',
  resourceNotFound: 'Resource not found',
  rolesRequired: 'Roles required',
  userCreateRoleNotFound: 'One of the roles is not a valid role',
  tokenRequired: 'Token required',
  userNotAuthenticated: 'User not authenticated',
  emailPasswordNotCorrect: 'Email or password is not correct',
  notAllowedToCreateAdmin: 'User is not allowed to create admin',
  tokenTypeRequired: 'Token type required',
  expiresInNotValid: 'Argument expiresIn is not valid',
  userIdRequired: 'User id is required',
  tokenInvalid: 'Token is invalid',
  startDateRequired: 'Start Date required',
  endDateRequired: 'End Date required',
  payRateRequired: 'PayRate required',
  clientNotFound: 'Client not found',
  clientCodeExists: 'Client code already exists',
  pleaseLoginWithClient: 'Please login with your respective client',
  invitationAlreadyExists: 'Invitation already exists',
  inviterRequired: 'Inviter required',
  clientRequired: 'Client required',
  userAlreadyExistsInClient: 'User already exists',
  notAllowedToPerformAction: 'User is not allowed to perform the action',
  canOnlyInviteToOwnClient: 'User can only invite to its own workspace',
  canOnlyViewOwnClient: 'User can only view its own client invitations',
  canOnlyCreateOnOwnClient: 'User can only create on its own workspace',
  recordRequired: 'Record is required',
  nameRequired: 'Name required',
  managerIdRequired: 'Manager Id required',
  clientIdRequired: 'Client Id required',
  statusRequired: 'Status Required',
  taskIdRequired: 'Task Id required',
  EmployeeIdRequired: 'Employee Id required',
  taskNotFound: 'Task not found',
  invitationNotFound: 'Invitation not found',
  roleRequired: 'Role required',
  invitationExpired: 'Invitation expired',
};
