export default {
  userAlreadyExists: 'User already exists',
  idRequired: 'Id is required',
  userNotFound: 'User not found',
  emailRequired: 'Email required',
  passwordRequired: 'Password required',
  firstNameRequired: 'Firstname required',
  lastNameRequired: 'Lastname required',
  emailNotValid: 'Email not valid',
  phoneRequired: 'Phone required',
  resourceNotFound: 'Resource not found',
  rolesRequired: 'Roles required',
  userCreateRoleNotFound: 'One of the roles is not a valid role',
  tokenRequired: 'Token required',
  userNotAuthenticated: 'User not authenticated',
  emailPasswordNotCorrect: 'Email or password is not correct',
};
